Add parsing partner db basic functions
ivanrod-gh/book-search pull request #1
Opened 2023-09-05 16:56 UTC by ivanrod-gh

2023-09-09 12:08 UTC, vkurennov requested changes

2023-09-09 12:08 UTC, vkurennov commented on app/models/author.rb
> +  validates :int_id, presence: true, uniqueness: true
не стоит имена сокращать,  что такое int? internal? international? integer? пиши полностью

2023-09-09 12:08 UTC, vkurennov commented on spec/services/partner_d_b_download_spec.rb
> +  it 'downloads partner db' do
этот тест не проверяет поведение сервиса. все что он проверяет, что был вызван метод call, если вызвать метод call. это бессмысленный тест. ты же сам у класса в тесте вызваешь метод call, зачем это проверять?

А вот что должен **сделать** вызов этого метода? Вот что нужно проверить

2023-09-09 12:08 UTC, vkurennov commented on spec/services/partner_d_b_parse_spec.rb
> +      Services::PartnerDBParse.new(task_detailed_db).call
тут немного неочевидно, почему task_detailed_db не добавляет в базу ничего?

2023-09-11 14:33 UTC, ivanrod-gh commented on app/models/author.rb
> +  validates :int_id, presence: true, uniqueness: true
Этот 'int_id' взялся не на пустом месте, а из скачиваемой детальной БД: "...<art int_id="121281" added="2007-07-25 19:28:33" price="79.99"...". Оттуда же 'art', 'offer' и т.д. Сделано так, чтобы не путаться и не плодить сущности. Если прям настаиваешь, поменяю

2023-09-20 11:36 UTC, merged